### PR TITLE
Updating logos for OKF press resources page

### PR DESCRIPTION
**Pull request by StephenAbbott**

### CODE REVIEW

**Comment by roll** [comment]
@amercader 
@StephenAbbott 
Do you have some clue why there are merging conflicts? Have we run into something like this before?

**Comment by StephenAbbott** [comment]
@roll @amercader Most new logos showing up on https://okfn.org/about/press/resources as they should now. 

But there is an extra slot in the Small use logo row which is still showing the old logo. Perhaps the conflicts were because I didn't overwrite that image? Or perhaps we can just fix the small-full file in question?

**Comment by amercader** [comment]
@roll I think that the conflicts are just git not liking the changes. We should just accept the new changes to resolve them. It's fine to merge this, IIRC there is an automated job to upload the assets to S3

**Comment by roll** [comment]
Closing as the merge conflicts are not resolvable

As an alternative #8

**Pull request closed without merging**
